name: Build and Push Docker Compose Images

on:
  push:
    tags:
      - 'v*'   # Only trigger on version tags
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag (e.g., v3.11.0)'
        required: true
        default: 'v3.11.0'

env:
  REGISTRY: docker.io
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }} 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Set TAG_VERSION
        id: set_tag
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "TAG_VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          else
            echo "TAG_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
          fi

      - name: Use TAG_VERSION
        run: |
          echo "The tag version is $TAG_VERSION"
          
      - name: Checkout repository at specific tag
        uses: actions/checkout@v4
        with:
          ref: "${{ env.TAG_VERSION }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build services
        run: |
          docker compose build

      - name: Tag and push images
        run: |
          # Define your custom mapping here
          declare -A IMAGE_MAP=(
            [openas2app-openas2]=${{ secrets.DOCKERHUB_USERNAME }}/openas2
            [openas2app-openas2_webui]=${{ secrets.DOCKERHUB_USERNAME }}/openas2_webui
          )

          for service in "${!IMAGE_MAP[@]}"; do
            full_image_name=${IMAGE_MAP[$service]}

            echo "Tagging $service as $full_image_name:${{ env.TAG_VERSION }} and $full_image_name:latest"

            docker tag $service $full_image_name:${{ env.TAG_VERSION }}
            docker push $full_image_name:${{ env.TAG_VERSION }}

            docker tag $service $full_image_name:latest
            docker push $full_image_name:latest
          done
